33 rest api for reservations
Timplayer/SWSYSPRO-Projekt pull request #43
Opened 2024-06-17 18:03 UTC by AlphaLEXray

2024-06-23 12:55 UTC, Niko4u5 commented
Es fehlen noch tests

2024-06-23 12:56 UTC, Niko4u5 requested changes
tests fehlen

2024-06-25 16:35 UTC, AlphaLEXray commented
Denke schon.

2024-06-25 17:41 UTC, Niko4u5 approved these changes

2024-06-25 17:41 UTC, merged